### ISSUE TITLE
error running test.sh

### ISSUE THREAD

**Issue by hernandezvargash** [lnscan/mitoSplitter#1]
Thank you for this interesting tool.
After installation I tried to run the example and got this error:

`../mitoSplitter_pipeline.sh: 75: [[: not found
../mitoSplitter_pipeline.sh: 78: [[: not found
ERROR:Bulk mtRNA matrix path and bulk RNA-seq bam list file cannot both be missing!`

I installed in conda environment without any issues and after activating the environment switched to the 'example_data' directory, as described. Samtools is installed on my PATH.
Any idea what went wrong?

**Comment by lnscan** [comment]
您的邮件 林 已经收到，尽快回复，谢谢。

**Comment by lnscan** [comment]
Thank you for your question, please change "sh test.sh" to "bash test.sh"，and run the script again.
This may be due to subtle differences in "sh" between different Linux operating systems.

**Comment by hernandezvargash** [comment]
thanks for the quick response!
yes, your suggestion worked, but only after changing "sh" to "bash" also on the "text.sh" code like this:

`#!/bin/bash

## test run of mitoSplitter, all cells in the example_data are singlets

bash ../mitoSplitter_pipeline.sh -i sc_mix.bam -b barcodes.list -o example_result -l bam_file.list -g barcodes_cluster.txt test.log 2>&1 &`

this time the script starts running after "bash test.sh".

I then get many messages of this type: `[E::idx_find_and_load] Could not retrieve index file for 'example_result/bam_split_by_bc0/TCGCAGCTAGCTCA-1.bam'`

The run finally freezes on this error: `ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.`
I still get 17 new files created within the "example_results" directory, including what looks like single cell barcode matrices.

Is this what I should expect?

**Comment by hernandezvargash** [comment]
follow-up on this:
I downgraded Numba within my "mitoSplitter" environment with `pip install numba==0.53`.
I still get the "could not retrieve index" messages, but not anymore the "ImportError: Numba".
19 items are created in my "example_results" folder, and I get a new error:
`ModuleNotFoundError: No module named 'skmisc'`
I'll install this and try again...

**Comment by hernandezvargash** [comment]
success (I think) after installing old version of scikit-misc, I reach the end of the script with several warnings and these two lines:
`example_result/mitoSplitter end at 2023-11-04 13:40:22
example_result/mitoSplitter running time 3.239386796951294 seconds.`
My "example_results" has now 13 files populating the "mitoSplitter" subdirectory, including a tSNE pdf.

To summarize:

- changed "sh" command to "bash"
- replace sh to bash also on the "test.sh" file
- add numba==0.53 to requirements
- add scikit-misc==0.1.4 to requirements

For info, I'm running a mamba environment in Ubuntu 22.04.
I'll try now on my own samples.
Thanks!

**Comment by lnscan** [comment]
Nice to see the problem resolved. Thank you for being so patient in debugging and summarizing.
I will make corresponding adjustments based on this information.

**Comment by IBDgenomics** [comment]
Having exactly the same issue as hernandezvargash here. My installation is in a computer cluster administered by third parties, so I'll check with them if this solution is feasible. 

Thanks hernandezvargash for reporting this, would be great to know how the tools works on your real data.
Thanks!
